2020-05-06 15:39:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "null"; SQL statement:
select comment0_.commentid as commenti1_2_, comment0_.article_news_id as article_7_2_, comment0_.comment_content as comment_2_2_, comment0_.comment_name as comment_3_2_, comment0_.create_date as create_d4_2_, comment0_.parentid as parentid5_2_, comment0_.parent_name as parent_n6_2_ from comment comment0_ where ARTICLE_NEWS_ID=? and PARENTID='null' [22018-200]
2020-05-07 15:10:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Value too long for column "CONTENT VARCHAR(500)": "STRINGDECODE('  \u672c\u8bfe\u9898\u91c7\u7528\u7684\u662fJava\u8bed\u8a00\u8fdb\u884c\u670d\u52a1\u7aef\u4e0eModel\u7684\u7f16\... (548)"; SQL statement:
insert into article (content, create_date, news_title, type_type_id, news_id) values (?, ?, ?, ?, ?) [22001-200]
2020-05-09 17:27:55 jdbc[15]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:719)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:705)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 18 more
